### ISSUE TITLE
name_to_sid returns 0 length vector

### ISSUE THREAD

**Issue by emily33901** [trailofbits/windows-acl#13]
It gets the right length, creates a new vector with that capacity, fills it up but never sets its length...

**Comment by woodruffw** [comment]
Thanks. Yeah, it looks like we're missing a `set_len` call on the `sid` that we return. I'll fix it on Monday.

**Comment by woodruffw** [comment]
Fixed with #14. I'll do a rollup of recent changes into a 0.3.0 release in a moment.

**Comment by woodruffw** [comment]
Cut with 0.3.0. Thanks again, and let us know if you have any other issues!
